import turtle
turtle.color('blue')
turtle.begin_fill()
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.end_fill()
turtle.penup()
turtle.forward(225)
turtle.pendown()
turtle.color('orange')
turtle.begin_fill()
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.hideturtle()
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.end_fill()
turtle.penup()
turtle.forward(225)
turtle.pendown()
turtle.color('green')
turtle.begin_fill()
turtle.right(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.hideturtle()
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.end_fill()
turtle.penup()
turtle.right(90)
turtle.forward(25)
turtle.pendown()
turtle.color('red')
turtle.begin_fill()
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(200)
turtle.end_fill()






